
FROM golang:1.24 AS builder
WORKDIR /app
# COPY ./app/lib_go/ .
COPY ./app/ .
RUN CGO_ENABLED=0 GOOS=linux go build -o /lib_app

FROM alpine:latest
# FROM scratch
COPY --from=builder /lib_app /lib_app
COPY --from=builder /app/templates/ /templates/
COPY --from=builder /app/static/ /static/
EXPOSE 8080

CMD ["/lib_app"]
