
name: ph_system_${ENV_NAME}

services:

  mongo:
    # image: mongo:3.2
    # image: mongo:3.4
    image: mongo:3.6
    restart: always
    container_name: ph_system_mongo_${ENV_NAME}
    expose:
      - "27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db
      # - ../data/mongo_db:/data/db
      # - ../data/mongo_dump:/data/dump
    networks:
      - frontend
      - mongo


  clojure:
    restart: always
    container_name: ph_system_clojure_${ENV_NAME}
    build: 
      context: ./clojure
      dockerfile: Dockerfile_Clojure
    # ports:
    #   - '9000:9000'
    expose:
      - "9000"
    volumes:
      # - ./app:/usr/src/app
      - ./app/lib:/usr/src/app
    environment:
      IPACS_DOMAIN_NAME: ${IPACS_DOMAIN_NAME}
      COMS_DOMAIN_NAME: ${COMS_DOMAIN_NAME}
      CAP_DOMAIN_NAME: ${CAP_DOMAIN_NAME}
      LIB_DOMAIN_NAME: ${LIB_DOMAIN_NAME}
      CONF_DOMAIN_NAME: ${CONF_DOMAIN_NAME}
      ALBUM_DOMAIN_NAME: ${ALBUM_DOMAIN_NAME}
      VIRTUAL_HOST:
        ${LIB_DOMAIN_NAME},
        # lib.physcon.my, lib.physcon.ru,
    networks:
      - frontend
      - mongo
    links:
      - mongo


# >>>
  nginx:
    restart: always
    container_name: ph_system_web_${ENV_NAME}
    build: 
      context: ./nginx
      dockerfile: Dockerfile_Nginx
    expose:
      - "80"
    volumes:
      - ./app/coms:/var/www/html
      - backup:/data/backup
    secrets:
      - htpasswd-coms
    environment:
      VIRTUAL_HOST:
        ${COMS_DOMAIN_NAME},
    networks:
      - frontend
      - php
    links:
      - php-fpm

  php-fpm:
    restart: always
    container_name: ph_system_php_${ENV_NAME}
    build: 
      context: ./php
      dockerfile: Dockerfile_PhpFpm
    expose:
      - "9000"
    volumes:
      - ./app/coms:/var/www/html
      - coms-papers:/data/papers
      - backup:/data/backup
    networks:
      - php
      - pg
      - smtp

  php-cron:
    restart: always
    container_name: ph_system_cron_${ENV_NAME}
    build: 
      context: ./php
      dockerfile: Dockerfile_PhpCron
    volumes:
      - ./app/coms:/var/www/html
      - coms-papers:/data/papers
    networks:
      - php
      - pg
      - smtp

  postgres:
    restart: always
    container_name: ph_system_pg_${ENV_NAME}
    build: 
      context: ./pg
      dockerfile: Dockerfile_Pg
    volumes:
      - pg-data:/var/lib/postgresql/data
      - backup:/data/backup
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    expose:
      - "5432"
    networks:
      - pg

  postfix:
    restart: always
    container_name: ph_system_mail_${ENV_NAME}
    build: 
      context: ./postfix
      dockerfile: Dockerfile
    expose:
      - "25"
    environment:
      maildomain: ${IPACS_DOMAIN_NAME}
      smtp_user: sender:love
    secrets:
      - mail.private
    networks:
      - smtp

  # api:
  #   restart: always
  #   container_name: ph_system_api_${ENV_NAME}
  #   build: 
  #     context: ./api
  #     dockerfile: Dockerfile_API
  #   stdin_open: true # docker run -i
  #   tty: true        # docker run -t
  #   volumes:
  #     - ./app/api:/app
  #   expose:
  #     - "5000"
  #   environment:
  #     VIRTUAL_HOST:
  #       ${API_DOMAIN_NAME}
  #     POSTGRES_USER: "root"
  #     POSTGRES_PASSWORD: "root"
  #   # ports:
  #   #   - "5000:5000"
  #   networks:
  #     - frontend
  #     - pg
  #     - mongo

# <<<


  # admin-nginx:
  #   restart: always
  #   container_name: ph_system_admin_${ENV_NAME}
  #   build: 
  #     context: ./admin_nginx
  #     dockerfile: Dockerfile_Nginx
  #   expose:
  #     - "80"
  #   volumes:
  #     - ./app/admin:/var/www/html
  #     - backup:/data/backup
  #   environment:
  #     VIRTUAL_HOST:
  #       ${ADMIN_DOMAIN_NAME},
  #   networks:
  #     - frontend





secrets:
  mail.private:
    file: .secrets/domainkeys/mail.private
  htpasswd-coms:
    file: .secrets/web/htpasswd-coms

volumes:
  mongo-data:
  pg-data:
  coms-papers:
  opendkim-domainkeys:
  backup:

networks:
  frontend:
    external: true 
    name: frontend 
  mongo:
  php:
  pg:
  smtp:


 